#!/usr/bin/env bash
set -euo pipefail

make build

mkdir -p "$HOME/.emerald/bin"

cp ./emerald "$HOME/.emerald/bin/emerald"
cp ./iem "$HOME/.emerald/bin/iem"
cp ./emerald-sandbox-worker "$HOME/.emerald/bin/emerald-sandbox-worker"

BASHRC="$HOME/.bashrc"
touch "$BASHRC"

function bashrc-add-if-not-present() {
  grep -qxF "$1" "$BASHRC" || printf '%s\n' "$1" >> "$BASHRC"
}

bashrc-add-if-not-present 'export PATH="$PATH:$HOME/.emerald/bin"'
bashrc-add-if-not-present 'export GEM_HOME="$HOME/.emerald/vendor"'
bashrc-add-if-not-present 'export GEM_PATH="$HOME/.emerald/vendor"'
